[package]
name = "rusty-bot"
version = "0.1.0"
authors = ["Will Fombin <njundongw@gmail.com>"]
edition = "2018"


[dependencies]
chrono = "0.4"
itertools="0.10.0"
linked_hash_set = "0.1.4"
rand = "0.5.5"
maplit = "1.0.2"
serenity = "0.10"
dotenv = "0.15"
tracing = "0.1.23"
tracing-subscriber = "0.2"

[dependencies.tokio]
version = "1.0"
features = ["macros", "signal", "rt-multi-thread"]